// Code generated by internal/genaot; DO NOT EDIT.
//go:build aot

package pgwasm

import (
	"context"
	base "github.com/moriyoshi/pglite-go-aot/pgwasm/base"
	emcompat "github.com/moriyoshi/pglite-go/emscripten"
	"github.com/moriyoshi/pglite-go/vfs"
	api "github.com/tetratelabs/wazero/api"
	"io"
)

// host implements the env + WASI import interfaces: invoke_* trampolines
// call through the table; _emscripten_throw_longjmp is the no-op cooperative
// unwind driver; everything else routes through the shared emscripten
// handlers via disp.Invoke + the api.Module adapter.
type host struct {
	fs      *vfs.FS
	stdin   []byte
	capture *[]byte
	disp    *emcompat.AOTDispatch
}

func (h *host) mod(m *base.Module) api.Module {
	return emcompat.NewAOTModuleAdapter(func() []byte { return m.Memory }, func(n string, a []uint64) uint64 { return aotCall(m, n, a) })
}

func (h *host) Invoke_ii(m *base.Module, l0 int32, l1 int32) int32 {
	return m.T0[l0].(func(*base.Module, int32) int32)(m, l1)
}

func (h *host) Invoke_vii(m *base.Module, l0 int32, l1 int32, l2 int32) {
	m.T0[l0].(func(*base.Module, int32, int32))(m, l1, l2)
}

func (h *host) Invoke_viiiii(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32) {
	m.T0[l0].(func(*base.Module, int32, int32, int32, int32, int32))(m, l1, l2, l3, l4, l5)
}

func (h *host) Invoke_vi(m *base.Module, l0 int32, l1 int32) {
	m.T0[l0].(func(*base.Module, int32))(m, l1)
}

func (h *host) Invoke_v(m *base.Module, l0 int32) {
	m.T0[l0].(func(*base.Module))(m)
}

func (h *host) Invoke_iii(m *base.Module, l0 int32, l1 int32, l2 int32) int32 {
	return m.T0[l0].(func(*base.Module, int32, int32) int32)(m, l1, l2)
}

func (h *host) Invoke_viii(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32) {
	m.T0[l0].(func(*base.Module, int32, int32, int32))(m, l1, l2, l3)
}

func (h *host) Invoke_iiii(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32) int32 {
	return m.T0[l0].(func(*base.Module, int32, int32, int32) int32)(m, l1, l2, l3)
}

func (h *host) Invoke_jii(m *base.Module, l0 int32, l1 int32, l2 int32) int64 {
	return m.T0[l0].(func(*base.Module, int32, int32) int64)(m, l1, l2)
}

func (h *host) Invoke_iiiii(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32) int32 {
	return m.T0[l0].(func(*base.Module, int32, int32, int32, int32) int32)(m, l1, l2, l3, l4)
}

func (h *host) Invoke_i(m *base.Module, l0 int32) int32 {
	return m.T0[l0].(func(*base.Module) int32)(m)
}

func (h *host) Invoke_ji(m *base.Module, l0 int32, l1 int32) int64 {
	return m.T0[l0].(func(*base.Module, int32) int64)(m, l1)
}

func (h *host) Invoke_jiiiiiiiii(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32, l6 int32, l7 int32, l8 int32, l9 int32) int64 {
	return m.T0[l0].(func(*base.Module, int32, int32, int32, int32, int32, int32, int32, int32, int32) int64)(m, l1, l2, l3, l4, l5, l6, l7, l8, l9)
}

func (h *host) Invoke_jiiiiii(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32, l6 int32) int64 {
	return m.T0[l0].(func(*base.Module, int32, int32, int32, int32, int32, int32) int64)(m, l1, l2, l3, l4, l5, l6)
}

func (h *host) Invoke_viiii(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32) {
	m.T0[l0].(func(*base.Module, int32, int32, int32, int32))(m, l1, l2, l3, l4)
}

func (h *host) Invoke_iiiiiiiiiiiiii(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32, l6 int32, l7 int32, l8 int32, l9 int32, l10 int32, l11 int32, l12 int32, l13 int32) int32 {
	return m.T0[l0].(func(*base.Module, int32, int32, int32, int32, int32, int32, int32, int32, int32, int32, int32, int32, int32) int32)(m, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13)
}

func (h *host) Invoke_vji(m *base.Module, l0 int32, l1 int64, l2 int32) {
	m.T0[l0].(func(*base.Module, int64, int32))(m, l1, l2)
}

func (h *host) Invoke_viiji(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int64, l4 int32) {
	m.T0[l0].(func(*base.Module, int32, int32, int64, int32))(m, l1, l2, l3, l4)
}

func (h *host) Invoke_iiiij(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int64) int32 {
	return m.T0[l0].(func(*base.Module, int32, int32, int32, int64) int32)(m, l1, l2, l3, l4)
}

func (h *host) Invoke_vijiji(m *base.Module, l0 int32, l1 int32, l2 int64, l3 int32, l4 int64, l5 int32) {
	m.T0[l0].(func(*base.Module, int32, int64, int32, int64, int32))(m, l1, l2, l3, l4, l5)
}

func (h *host) Invoke_viji(m *base.Module, l0 int32, l1 int32, l2 int64, l3 int32) {
	m.T0[l0].(func(*base.Module, int32, int64, int32))(m, l1, l2, l3)
}

func (h *host) Invoke_iiiiii(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32) int32 {
	return m.T0[l0].(func(*base.Module, int32, int32, int32, int32, int32) int32)(m, l1, l2, l3, l4, l5)
}

func (h *host) Invoke_iiiiiiiii(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32, l6 int32, l7 int32, l8 int32) int32 {
	return m.T0[l0].(func(*base.Module, int32, int32, int32, int32, int32, int32, int32, int32) int32)(m, l1, l2, l3, l4, l5, l6, l7, l8)
}

func (h *host) Invoke_iiiiiiiiiiiiiiiiii(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32, l6 int32, l7 int32, l8 int32, l9 int32, l10 int32, l11 int32, l12 int32, l13 int32, l14 int32, l15 int32, l16 int32, l17 int32) int32 {
	return m.T0[l0].(func(*base.Module, int32, int32, int32, int32, int32, int32, int32, int32, int32, int32, int32, int32, int32, int32, int32, int32, int32) int32)(m, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14, l15, l16, l17)
}

func (h *host) Invoke_iiiiiii(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32, l6 int32) int32 {
	return m.T0[l0].(func(*base.Module, int32, int32, int32, int32, int32, int32) int32)(m, l1, l2, l3, l4, l5, l6)
}

func (h *host) Invoke_vj(m *base.Module, l0 int32, l1 int64) {
	m.T0[l0].(func(*base.Module, int64))(m, l1)
}

func (h *host) Invoke_iiiiiiiiii(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32, l6 int32, l7 int32, l8 int32, l9 int32) int32 {
	return m.T0[l0].(func(*base.Module, int32, int32, int32, int32, int32, int32, int32, int32, int32) int32)(m, l1, l2, l3, l4, l5, l6, l7, l8, l9)
}

func (h *host) Invoke_viij(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int64) {
	m.T0[l0].(func(*base.Module, int32, int32, int64))(m, l1, l2, l3)
}

func (h *host) Invoke_viiiiiiii(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32, l6 int32, l7 int32, l8 int32) {
	m.T0[l0].(func(*base.Module, int32, int32, int32, int32, int32, int32, int32, int32))(m, l1, l2, l3, l4, l5, l6, l7, l8)
}

func (h *host) Invoke_viiiiiiiii(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32, l6 int32, l7 int32, l8 int32, l9 int32) {
	m.T0[l0].(func(*base.Module, int32, int32, int32, int32, int32, int32, int32, int32, int32))(m, l1, l2, l3, l4, l5, l6, l7, l8, l9)
}

func (h *host) Invoke_vij(m *base.Module, l0 int32, l1 int32, l2 int64) {
	m.T0[l0].(func(*base.Module, int32, int64))(m, l1, l2)
}

func (h *host) Invoke_viiiiii(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32, l6 int32) {
	m.T0[l0].(func(*base.Module, int32, int32, int32, int32, int32, int32))(m, l1, l2, l3, l4, l5, l6)
}

func (h *host) Invoke_iiji(m *base.Module, l0 int32, l1 int32, l2 int64, l3 int32) int32 {
	return m.T0[l0].(func(*base.Module, int32, int64, int32) int32)(m, l1, l2, l3)
}

func (h *host) Invoke_ij(m *base.Module, l0 int32, l1 int64) int32 {
	return m.T0[l0].(func(*base.Module, int64) int32)(m, l1)
}

func (h *host) Invoke_viiiiiii(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32, l6 int32, l7 int32) {
	m.T0[l0].(func(*base.Module, int32, int32, int32, int32, int32, int32, int32))(m, l1, l2, l3, l4, l5, l6, l7)
}

func (h *host) Invoke_viiiji(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int64, l5 int32) {
	m.T0[l0].(func(*base.Module, int32, int32, int32, int64, int32))(m, l1, l2, l3, l4, l5)
}

func (h *host) Invoke_iiiiiiii(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32, l6 int32, l7 int32) int32 {
	return m.T0[l0].(func(*base.Module, int32, int32, int32, int32, int32, int32, int32) int32)(m, l1, l2, l3, l4, l5, l6, l7)
}

func (h *host) Invoke_iiij(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int64) int32 {
	return m.T0[l0].(func(*base.Module, int32, int32, int64) int32)(m, l1, l2, l3)
}

func (h *host) Invoke_vid(m *base.Module, l0 int32, l1 int32, l2 float64) {
	m.T0[l0].(func(*base.Module, int32, float64))(m, l1, l2)
}

func (h *host) Getaddrinfo(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32) int32 {
	stack := make([]uint64, 4)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	h.disp.Invoke("getaddrinfo", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Invoke_j(m *base.Module, l0 int32) int64 {
	return m.T0[l0].(func(*base.Module) int64)(m)
}

func (h *host) Invoke_ijji(m *base.Module, l0 int32, l1 int64, l2 int64, l3 int32) int32 {
	return m.T0[l0].(func(*base.Module, int64, int64, int32) int32)(m, l1, l2, l3)
}

func (h *host) Invoke_iijj(m *base.Module, l0 int32, l1 int32, l2 int64, l3 int64) int32 {
	return m.T0[l0].(func(*base.Module, int32, int64, int64) int32)(m, l1, l2, l3)
}

func (h *host) Invoke_jiii(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32) int64 {
	return m.T0[l0].(func(*base.Module, int32, int32, int32) int64)(m, l1, l2, l3)
}

func (h *host) Invoke_jij(m *base.Module, l0 int32, l1 int32, l2 int64) int64 {
	return m.T0[l0].(func(*base.Module, int32, int64) int64)(m, l1, l2)
}

func (h *host) Invoke_ijiiiiii(m *base.Module, l0 int32, l1 int64, l2 int32, l3 int32, l4 int32, l5 int32, l6 int32, l7 int32) int32 {
	return m.T0[l0].(func(*base.Module, int64, int32, int32, int32, int32, int32, int32) int32)(m, l1, l2, l3, l4, l5, l6, l7)
}

func (h *host) Invoke_viijii(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int64, l4 int32, l5 int32) {
	m.T0[l0].(func(*base.Module, int32, int32, int64, int32, int32))(m, l1, l2, l3, l4, l5)
}

func (h *host) Invoke_iiiiiji(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int64, l6 int32) int32 {
	return m.T0[l0].(func(*base.Module, int32, int32, int32, int32, int64, int32) int32)(m, l1, l2, l3, l4, l5, l6)
}

func (h *host) Invoke_viijiiii(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int64, l4 int32, l5 int32, l6 int32, l7 int32) {
	m.T0[l0].(func(*base.Module, int32, int32, int64, int32, int32, int32, int32))(m, l1, l2, l3, l4, l5, l6, l7)
}

func (h *host) Invoke_vijjii(m *base.Module, l0 int32, l1 int32, l2 int64, l3 int64, l4 int32, l5 int32) {
	m.T0[l0].(func(*base.Module, int32, int64, int64, int32, int32))(m, l1, l2, l3, l4, l5)
}

func (h *host) Invoke_vjii(m *base.Module, l0 int32, l1 int64, l2 int32, l3 int32) {
	m.T0[l0].(func(*base.Module, int64, int32, int32))(m, l1, l2, l3)
}

func (h *host) Invoke_jiiii(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32) int64 {
	return m.T0[l0].(func(*base.Module, int32, int32, int32, int32) int64)(m, l1, l2, l3, l4)
}

func (h *host) Invoke_viiiiiiiiiiii(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32, l6 int32, l7 int32, l8 int32, l9 int32, l10 int32, l11 int32, l12 int32) {
	m.T0[l0].(func(*base.Module, int32, int32, int32, int32, int32, int32, int32, int32, int32, int32, int32, int32))(m, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12)
}

func (h *host) X__assert_fail(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32) {
	stack := make([]uint64, 4)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	h.disp.Invoke("__assert_fail", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f}, []byte{})
}

func (h *host) Invoke_di(m *base.Module, l0 int32, l1 int32) float64 {
	return m.T0[l0].(func(*base.Module, int32) float64)(m, l1)
}

func (h *host) Invoke_id(m *base.Module, l0 int32, l1 float64) int32 {
	return m.T0[l0].(func(*base.Module, float64) int32)(m, l1)
}

func (h *host) Invoke_ijiiiii(m *base.Module, l0 int32, l1 int64, l2 int32, l3 int32, l4 int32, l5 int32, l6 int32) int32 {
	return m.T0[l0].(func(*base.Module, int64, int32, int32, int32, int32, int32) int32)(m, l1, l2, l3, l4, l5, l6)
}

func (h *host) Invoke_iiiiiiiiiii(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32, l6 int32, l7 int32, l8 int32, l9 int32, l10 int32) int32 {
	return m.T0[l0].(func(*base.Module, int32, int32, int32, int32, int32, int32, int32, int32, int32, int32) int32)(m, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10)
}

func (h *host) Getnameinfo(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32, l6 int32) int32 {
	stack := make([]uint64, 7)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	stack[4] = api.EncodeI32(l4)
	stack[5] = api.EncodeI32(l5)
	stack[6] = api.EncodeI32(l6)
	h.disp.Invoke("getnameinfo", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f, 0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Exit(m *base.Module, l0 int32) {
	stack := make([]uint64, 1)
	stack[0] = api.EncodeI32(l0)
	h.disp.Invoke("exit", h.mod(m), stack, []byte{0x7f}, []byte{})
}

func (h *host) X_tzset_js(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32) {
	stack := make([]uint64, 4)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	h.disp.Invoke("_tzset_js", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f}, []byte{})
}

func (h *host) X_abort_js(m *base.Module) {
	stack := make([]uint64, 0)
	h.disp.Invoke("_abort_js", h.mod(m), stack, []byte{}, []byte{})
}

func (h *host) X__syscall_faccessat(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32) int32 {
	stack := make([]uint64, 4)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	h.disp.Invoke("__syscall_faccessat", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_chdir(m *base.Module, l0 int32) int32 {
	stack := make([]uint64, 1)
	stack[0] = api.EncodeI32(l0)
	h.disp.Invoke("__syscall_chdir", h.mod(m), stack, []byte{0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_chmod(m *base.Module, l0 int32, l1 int32) int32 {
	stack := make([]uint64, 2)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	h.disp.Invoke("__syscall_chmod", h.mod(m), stack, []byte{0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_fchownat(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32) int32 {
	stack := make([]uint64, 5)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	stack[4] = api.EncodeI32(l4)
	h.disp.Invoke("__syscall_fchownat", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_dup(m *base.Module, l0 int32) int32 {
	stack := make([]uint64, 1)
	stack[0] = api.EncodeI32(l0)
	h.disp.Invoke("__syscall_dup", h.mod(m), stack, []byte{0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_dup3(m *base.Module, l0 int32, l1 int32, l2 int32) int32 {
	stack := make([]uint64, 3)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	h.disp.Invoke("__syscall_dup3", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X_dlopen_js(m *base.Module, l0 int32) int32 {
	stack := make([]uint64, 1)
	stack[0] = api.EncodeI32(l0)
	h.disp.Invoke("_dlopen_js", h.mod(m), stack, []byte{0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X_dlsym_js(m *base.Module, l0 int32, l1 int32, l2 int32) int32 {
	stack := make([]uint64, 3)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	h.disp.Invoke("_dlsym_js", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Emscripten_date_now(m *base.Module) float64 {
	stack := make([]uint64, 1)
	h.disp.Invoke("emscripten_date_now", h.mod(m), stack, []byte{}, []byte{0x7c})
	return api.DecodeF64(stack[0])
}

func (h *host) X__syscall_fdatasync(m *base.Module, l0 int32) int32 {
	stack := make([]uint64, 1)
	stack[0] = api.EncodeI32(l0)
	h.disp.Invoke("__syscall_fdatasync", h.mod(m), stack, []byte{0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_openat(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32) int32 {
	stack := make([]uint64, 4)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	h.disp.Invoke("__syscall_openat", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_fcntl64(m *base.Module, l0 int32, l1 int32, l2 int32) int32 {
	stack := make([]uint64, 3)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	h.disp.Invoke("__syscall_fcntl64", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_ioctl(m *base.Module, l0 int32, l1 int32, l2 int32) int32 {
	stack := make([]uint64, 3)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	h.disp.Invoke("__syscall_ioctl", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_fstat64(m *base.Module, l0 int32, l1 int32) int32 {
	stack := make([]uint64, 2)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	h.disp.Invoke("__syscall_fstat64", h.mod(m), stack, []byte{0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_stat64(m *base.Module, l0 int32, l1 int32) int32 {
	stack := make([]uint64, 2)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	h.disp.Invoke("__syscall_stat64", h.mod(m), stack, []byte{0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_newfstatat(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32) int32 {
	stack := make([]uint64, 4)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	h.disp.Invoke("__syscall_newfstatat", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_lstat64(m *base.Module, l0 int32, l1 int32) int32 {
	stack := make([]uint64, 2)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	h.disp.Invoke("__syscall_lstat64", h.mod(m), stack, []byte{0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_ftruncate64(m *base.Module, l0 int32, l1 int64) int32 {
	stack := make([]uint64, 2)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI64(l1)
	h.disp.Invoke("__syscall_ftruncate64", h.mod(m), stack, []byte{0x7f, 0x7e}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_getcwd(m *base.Module, l0 int32, l1 int32) int32 {
	stack := make([]uint64, 2)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	h.disp.Invoke("__syscall_getcwd", h.mod(m), stack, []byte{0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Emscripten_get_now(m *base.Module) float64 {
	stack := make([]uint64, 1)
	h.disp.Invoke("emscripten_get_now", h.mod(m), stack, []byte{}, []byte{0x7c})
	return api.DecodeF64(stack[0])
}

func (h *host) X__syscall_mkdirat(m *base.Module, l0 int32, l1 int32, l2 int32) int32 {
	stack := make([]uint64, 3)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	h.disp.Invoke("__syscall_mkdirat", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X_localtime_js(m *base.Module, l0 int64, l1 int32) {
	stack := make([]uint64, 2)
	stack[0] = api.EncodeI64(l0)
	stack[1] = api.EncodeI32(l1)
	h.disp.Invoke("_localtime_js", h.mod(m), stack, []byte{0x7e, 0x7f}, []byte{})
}

func (h *host) X_gmtime_js(m *base.Module, l0 int64, l1 int32) {
	stack := make([]uint64, 2)
	stack[0] = api.EncodeI64(l0)
	stack[1] = api.EncodeI32(l1)
	h.disp.Invoke("_gmtime_js", h.mod(m), stack, []byte{0x7e, 0x7f}, []byte{})
}

func (h *host) X_munmap_js(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int64) int32 {
	stack := make([]uint64, 6)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	stack[4] = api.EncodeI32(l4)
	stack[5] = api.EncodeI64(l5)
	h.disp.Invoke("_munmap_js", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f, 0x7f, 0x7e}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X_mmap_js(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int64, l5 int32, l6 int32) int32 {
	stack := make([]uint64, 7)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	stack[4] = api.EncodeI64(l4)
	stack[5] = api.EncodeI32(l5)
	stack[6] = api.EncodeI32(l6)
	h.disp.Invoke("_mmap_js", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f, 0x7e, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_pipe(m *base.Module, l0 int32) int32 {
	stack := make([]uint64, 1)
	stack[0] = api.EncodeI32(l0)
	h.disp.Invoke("__syscall_pipe", h.mod(m), stack, []byte{0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_fadvise64(m *base.Module, l0 int32, l1 int64, l2 int64, l3 int32) int32 {
	stack := make([]uint64, 4)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI64(l1)
	stack[2] = api.EncodeI64(l2)
	stack[3] = api.EncodeI32(l3)
	h.disp.Invoke("__syscall_fadvise64", h.mod(m), stack, []byte{0x7f, 0x7e, 0x7e, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_fallocate(m *base.Module, l0 int32, l1 int32, l2 int64, l3 int64) int32 {
	stack := make([]uint64, 4)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI64(l2)
	stack[3] = api.EncodeI64(l3)
	h.disp.Invoke("__syscall_fallocate", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7e, 0x7e}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X_emscripten_runtime_keepalive_clear(m *base.Module) {
	stack := make([]uint64, 0)
	h.disp.Invoke("_emscripten_runtime_keepalive_clear", h.mod(m), stack, []byte{}, []byte{})
}

func (h *host) X__call_sighandler(m *base.Module, l0 int32, l1 int32) {
	stack := make([]uint64, 2)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	h.disp.Invoke("__call_sighandler", h.mod(m), stack, []byte{0x7f, 0x7f}, []byte{})
}

func (h *host) X__syscall_getdents64(m *base.Module, l0 int32, l1 int32, l2 int32) int32 {
	stack := make([]uint64, 3)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	h.disp.Invoke("__syscall_getdents64", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_readlinkat(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32) int32 {
	stack := make([]uint64, 4)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	h.disp.Invoke("__syscall_readlinkat", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_renameat(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32) int32 {
	stack := make([]uint64, 4)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	h.disp.Invoke("__syscall_renameat", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_rmdir(m *base.Module, l0 int32) int32 {
	stack := make([]uint64, 1)
	stack[0] = api.EncodeI32(l0)
	h.disp.Invoke("__syscall_rmdir", h.mod(m), stack, []byte{0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall__newselect(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32) int32 {
	stack := make([]uint64, 5)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	stack[4] = api.EncodeI32(l4)
	h.disp.Invoke("__syscall__newselect", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X_setitimer_js(m *base.Module, l0 int32, l1 float64) int32 {
	stack := make([]uint64, 2)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeF64(l1)
	h.disp.Invoke("_setitimer_js", h.mod(m), stack, []byte{0x7f, 0x7c}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_symlinkat(m *base.Module, l0 int32, l1 int32, l2 int32) int32 {
	stack := make([]uint64, 3)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	h.disp.Invoke("__syscall_symlinkat", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Emscripten_get_heap_max(m *base.Module) int32 {
	stack := make([]uint64, 1)
	h.disp.Invoke("emscripten_get_heap_max", h.mod(m), stack, []byte{}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_truncate64(m *base.Module, l0 int32, l1 int64) int32 {
	stack := make([]uint64, 2)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI64(l1)
	h.disp.Invoke("__syscall_truncate64", h.mod(m), stack, []byte{0x7f, 0x7e}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_unlinkat(m *base.Module, l0 int32, l1 int32, l2 int32) int32 {
	stack := make([]uint64, 3)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	h.disp.Invoke("__syscall_unlinkat", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_utimensat(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32) int32 {
	stack := make([]uint64, 4)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	h.disp.Invoke("__syscall_utimensat", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Emscripten_resize_heap(m *base.Module, l0 int32) int32 {
	newLen := uint64(uint32(l0))
	if newLen <= m.MemSize.Load() {
		return 1
	}
	if newLen > uint64(cap(m.Memory)) {
		return 0
	}
	m.Memory = m.Memory[:newLen]
	m.MemSize.Store(newLen)
	return 1
}

func (h *host) X_emscripten_throw_longjmp(m *base.Module) {
	// cooperative unwind: __THREW__ already set; just return
}

func (h *host) X__syscall_accept4(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32) int32 {
	stack := make([]uint64, 6)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	stack[4] = api.EncodeI32(l4)
	stack[5] = api.EncodeI32(l5)
	h.disp.Invoke("__syscall_accept4", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_bind(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32) int32 {
	stack := make([]uint64, 6)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	stack[4] = api.EncodeI32(l4)
	stack[5] = api.EncodeI32(l5)
	h.disp.Invoke("__syscall_bind", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_connect(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32) int32 {
	stack := make([]uint64, 6)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	stack[4] = api.EncodeI32(l4)
	stack[5] = api.EncodeI32(l5)
	h.disp.Invoke("__syscall_connect", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_listen(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32) int32 {
	stack := make([]uint64, 6)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	stack[4] = api.EncodeI32(l4)
	stack[5] = api.EncodeI32(l5)
	h.disp.Invoke("__syscall_listen", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_recvfrom(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32) int32 {
	stack := make([]uint64, 6)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	stack[4] = api.EncodeI32(l4)
	stack[5] = api.EncodeI32(l5)
	h.disp.Invoke("__syscall_recvfrom", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_sendto(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32) int32 {
	stack := make([]uint64, 6)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	stack[4] = api.EncodeI32(l4)
	stack[5] = api.EncodeI32(l5)
	h.disp.Invoke("__syscall_sendto", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_socket(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32) int32 {
	stack := make([]uint64, 6)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	stack[4] = api.EncodeI32(l4)
	stack[5] = api.EncodeI32(l5)
	h.disp.Invoke("__syscall_socket", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_fchmod(m *base.Module, l0 int32, l1 int32) int32 {
	stack := make([]uint64, 2)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	h.disp.Invoke("__syscall_fchmod", h.mod(m), stack, []byte{0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_fchmodat2(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32) int32 {
	stack := make([]uint64, 4)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	h.disp.Invoke("__syscall_fchmodat2", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_fchown32(m *base.Module, l0 int32, l1 int32, l2 int32) int32 {
	stack := make([]uint64, 3)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	h.disp.Invoke("__syscall_fchown32", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_statfs64(m *base.Module, l0 int32, l1 int32, l2 int32) int32 {
	stack := make([]uint64, 3)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	h.disp.Invoke("__syscall_statfs64", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Environ_sizes_get(m *base.Module, l0 int32, l1 int32) int32 {
	stack := make([]uint64, 2)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	h.disp.Invoke("environ_sizes_get", h.mod(m), stack, []byte{0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Environ_get(m *base.Module, l0 int32, l1 int32) int32 {
	stack := make([]uint64, 2)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	h.disp.Invoke("environ_get", h.mod(m), stack, []byte{0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Proc_exit(m *base.Module, l0 int32) {
	stack := make([]uint64, 1)
	stack[0] = api.EncodeI32(l0)
	h.disp.Invoke("proc_exit", h.mod(m), stack, []byte{0x7f}, []byte{})
}

func (h *host) Clock_time_get(m *base.Module, l0 int32, l1 int64, l2 int32) int32 {
	stack := make([]uint64, 3)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI64(l1)
	stack[2] = api.EncodeI32(l2)
	h.disp.Invoke("clock_time_get", h.mod(m), stack, []byte{0x7f, 0x7e, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Fd_close(m *base.Module, l0 int32) int32 {
	stack := make([]uint64, 1)
	stack[0] = api.EncodeI32(l0)
	h.disp.Invoke("fd_close", h.mod(m), stack, []byte{0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Fd_write(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32) int32 {
	stack := make([]uint64, 4)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	h.disp.Invoke("fd_write", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Fd_read(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32) int32 {
	stack := make([]uint64, 4)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	h.disp.Invoke("fd_read", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Fd_sync(m *base.Module, l0 int32) int32 {
	stack := make([]uint64, 1)
	stack[0] = api.EncodeI32(l0)
	h.disp.Invoke("fd_sync", h.mod(m), stack, []byte{0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Fd_fdstat_get(m *base.Module, l0 int32, l1 int32) int32 {
	stack := make([]uint64, 2)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	h.disp.Invoke("fd_fdstat_get", h.mod(m), stack, []byte{0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Fd_seek(m *base.Module, l0 int32, l1 int64, l2 int32, l3 int32) int32 {
	stack := make([]uint64, 4)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI64(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	h.disp.Invoke("fd_seek", h.mod(m), stack, []byte{0x7f, 0x7e, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Fd_pread(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int64, l4 int32) int32 {
	stack := make([]uint64, 5)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI64(l3)
	stack[4] = api.EncodeI32(l4)
	h.disp.Invoke("fd_pread", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7e, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Fd_pwrite(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int64, l4 int32) int32 {
	stack := make([]uint64, 5)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI64(l3)
	stack[4] = api.EncodeI32(l4)
	h.disp.Invoke("fd_pwrite", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7e, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Random_get(m *base.Module, l0 int32, l1 int32) int32 {
	stack := make([]uint64, 2)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	h.disp.Invoke("random_get", h.mod(m), stack, []byte{0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

type aotModule struct {
	m    *base.Module
	disp *emcompat.AOTDispatch
}

func (a *aotModule) Memory() []byte              { return a.m.Memory }
func (a *aotModule) ApplyDataRelocs()            { WasmApplyDataRelocs(a.m) }
func (a *aotModule) CallCtors()                  { WasmCallCtors(a.m) }
func (a *aotModule) SP() int32                   { return a.m.G1 }
func (a *aotModule) SetSP(v int32)               { a.m.G1 = v }
func (a *aotModule) SetStdout(w io.Writer)       { a.disp.SetStdout(w) }
func (a *aotModule) SetStderr(w io.Writer)       { a.disp.SetStderr(w) }
func (a *aotModule) SetStdoutCapture(bb *[]byte) { a.disp.SetStdoutCapture(bb) }

func (a *aotModule) Call(name string, args []uint64) uint64 { return aotCall(a.m, name, args) }

// aotCall dispatches an exported function by name (wasm value lanes).
func aotCall(m *base.Module, name string, args []uint64) uint64 {
	switch name {
	case "emscripten_builtin_memalign":
		return uint64(uint32(EmscriptenBuiltinMemalign(m, aotI32(args[0]), aotI32(args[1]))))
	case "malloc":
		return uint64(uint32(Malloc(m, aotI32(args[0]))))
	case "pgl_getMyProcPort":
		return uint64(uint32(PglGetMyProcPort(m)))
	case "pgl_set_popen_fn":
		PglSetPopenFn(m, aotI32(args[0]))
		return 0
	case "ProcessStartupPacket":
		return uint64(uint32(ProcessStartupPacket(m, aotI32(args[0]), aotI32(args[1]), aotI32(args[2]))))
	case "PostgresMainLoopOnce":
		PostgresMainLoopOnce(m)
		return 0
	case "PostgresSendReadyForQueryIfNecessary":
		PostgresSendReadyForQueryIfNecessary(m)
		return 0
	case "pgl_startPGlite":
		PglStartPGlite(m)
		return 0
	case "pgl_pq_flush":
		PglPqFlush(m)
		return 0
	case "__main_argc_argv":
		return uint64(uint32(MainArgcArgv(m, aotI32(args[0]), aotI32(args[1]))))
	case "pgl_set_system_fn":
		PglSetSystemFn(m, aotI32(args[0]))
		return 0
	case "PostgresMainLongJmp":
		PostgresMainLongJmp(m)
		return 0
	case "__wasm_call_ctors":
		WasmCallCtors(m)
		return 0
	case "__wasm_apply_data_relocs":
		WasmApplyDataRelocs(m)
		return 0
	case "pgl_setPGliteActive":
		return uint64(uint32(PglSetPGliteActive(m, aotI32(args[0]))))
	case "pgl_set_rw_cbs":
		PglSetRwCbs(m, aotI32(args[0]), aotI32(args[1]))
		return 0
	case "pgl_set_pclose_fn":
		PglSetPcloseFn(m, aotI32(args[0]))
		return 0
	case "pq_buffer_remaining_data":
		return uint64(uint32(PqBufferRemainingData(m)))
	default:
		panic("aot: unknown export " + name)
	}
}

// RegisterRW appends the socket read/write callbacks (ptr i32, len i32 -> i32,
// matching the wazero backend) and returns the base index.
func (a *aotModule) RegisterRW(read func(dst []byte) int, write func(src []byte)) uint32 {
	idx := uint32(len(a.m.T0))
	readFn := func(m *base.Module, ptr, max int32) int32 {
		tmp := make([]byte, max)
		n := read(tmp)
		if n > 0 {
			copy(m.Memory[ptr:ptr+int32(n)], tmp[:n])
		}
		return int32(n)
	}
	writeFn := func(m *base.Module, ptr, length int32) int32 {
		write(m.Memory[ptr : ptr+length])
		return length
	}
	a.m.T0 = append(a.m.T0, readFn, writeFn)
	return idx
}

// RegisterInitdb gives the callbacks module access (readCString, Fopen via
// exports) and appends the system/popen/pclose table entries.
func (a *aotModule) RegisterInitdb(cb *emcompat.InitdbCallbacks) uint32 {
	cb.SetModule(emcompat.NewAOTModuleAdapter(func() []byte { return a.m.Memory }, func(n string, ar []uint64) uint64 { return aotCall(a.m, n, ar) }))
	idx := uint32(len(a.m.T0))
	systemFn := func(m *base.Module, cmd int32) int32 {
		return cb.OnSystem(context.Background(), aotCStr(m.Memory, cmd))
	}
	popenFn := func(m *base.Module, cmd, mode int32) int32 {
		return cb.OnPopen(context.Background(), aotCStr(m.Memory, cmd), aotCStr(m.Memory, mode))
	}
	pcloseFn := func(m *base.Module, stream int32) int32 {
		return cb.OnPclose(context.Background(), stream)
	}
	a.m.T0 = append(a.m.T0, systemFn, popenFn, pcloseFn)
	return idx
}

func aotCStr(mem []byte, ptr int32) string {
	if ptr == 0 {
		return ""
	}
	end := int(ptr)
	for end < len(mem) && mem[end] != 0 {
		end++
	}
	return string(mem[ptr:end])
}

// NewAOT wires the host adapter, instantiates the transpiled module with
// headroom for emscripten_resize_heap to grow by reslicing (no realloc,
// so cached m.M stays valid), and returns it as an emcompat.AOTModule.
func NewAOT(fs *vfs.FS, stdin []byte, capture *[]byte) emcompat.AOTModule {
	h := &host{fs: fs, stdin: stdin, capture: capture, disp: emcompat.NewAOTDispatch(fs, stdin, capture)}
	return &aotModule{m: NewWithWASIReserve(h, h, 768<<20), disp: h.disp}
}

func aotI32(v uint64) int32 { return int32(uint32(v)) }

var _ = context.Background
