// Code generated by internal/genaot; DO NOT EDIT.
//go:build aot

package initdbwasm

import (
	"context"
	emcompat "github.com/moriyoshi/pglite-go/emscripten"
	"github.com/moriyoshi/pglite-go/vfs"
	api "github.com/tetratelabs/wazero/api"
	"io"
)

// host implements the env + WASI import interfaces: invoke_* trampolines
// call through the table; _emscripten_throw_longjmp is the no-op cooperative
// unwind driver; everything else routes through the shared emscripten
// handlers via disp.Invoke + the api.Module adapter.
type host struct {
	fs      *vfs.FS
	stdin   []byte
	capture *[]byte
	disp    *emcompat.AOTDispatch
}

func (h *host) mod(m *Module) api.Module {
	return emcompat.NewAOTModuleAdapter(func() []byte { return m.memory }, func(n string, a []uint64) uint64 { return aotCall(m, n, a) })
}

func (h *host) Getaddrinfo(m *Module, l0 int32, l1 int32, l2 int32, l3 int32) int32 {
	stack := make([]uint64, 4)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	h.disp.Invoke("getaddrinfo", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Exit(m *Module, l0 int32) {
	stack := make([]uint64, 1)
	stack[0] = api.EncodeI32(l0)
	h.disp.Invoke("exit", h.mod(m), stack, []byte{0x7f}, []byte{})
}

func (h *host) Invoke_iiii(m *Module, l0 int32, l1 int32, l2 int32, l3 int32) int32 {
	return m.t0[l0].(func(*Module, int32, int32, int32) int32)(m, l1, l2, l3)
}

func (h *host) Invoke_ii(m *Module, l0 int32, l1 int32) int32 {
	return m.t0[l0].(func(*Module, int32) int32)(m, l1)
}

func (h *host) Invoke_vii(m *Module, l0 int32, l1 int32, l2 int32) {
	m.t0[l0].(func(*Module, int32, int32))(m, l1, l2)
}

func (h *host) X_tzset_js(m *Module, l0 int32, l1 int32, l2 int32, l3 int32) {
	stack := make([]uint64, 4)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	h.disp.Invoke("_tzset_js", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f}, []byte{})
}

func (h *host) X_abort_js(m *Module) {
	stack := make([]uint64, 0)
	h.disp.Invoke("_abort_js", h.mod(m), stack, []byte{}, []byte{})
}

func (h *host) X__syscall_faccessat(m *Module, l0 int32, l1 int32, l2 int32, l3 int32) int32 {
	stack := make([]uint64, 4)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	h.disp.Invoke("__syscall_faccessat", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_chmod(m *Module, l0 int32, l1 int32) int32 {
	stack := make([]uint64, 2)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	h.disp.Invoke("__syscall_chmod", h.mod(m), stack, []byte{0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Emscripten_date_now(m *Module) float64 {
	stack := make([]uint64, 1)
	h.disp.Invoke("emscripten_date_now", h.mod(m), stack, []byte{}, []byte{0x7c})
	return api.DecodeF64(stack[0])
}

func (h *host) X__syscall_openat(m *Module, l0 int32, l1 int32, l2 int32, l3 int32) int32 {
	stack := make([]uint64, 4)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	h.disp.Invoke("__syscall_openat", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_fcntl64(m *Module, l0 int32, l1 int32, l2 int32) int32 {
	stack := make([]uint64, 3)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	h.disp.Invoke("__syscall_fcntl64", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_ioctl(m *Module, l0 int32, l1 int32, l2 int32) int32 {
	stack := make([]uint64, 3)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	h.disp.Invoke("__syscall_ioctl", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_dup3(m *Module, l0 int32, l1 int32, l2 int32) int32 {
	stack := make([]uint64, 3)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	h.disp.Invoke("__syscall_dup3", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_stat64(m *Module, l0 int32, l1 int32) int32 {
	stack := make([]uint64, 2)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	h.disp.Invoke("__syscall_stat64", h.mod(m), stack, []byte{0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_newfstatat(m *Module, l0 int32, l1 int32, l2 int32, l3 int32) int32 {
	stack := make([]uint64, 4)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	h.disp.Invoke("__syscall_newfstatat", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_lstat64(m *Module, l0 int32, l1 int32) int32 {
	stack := make([]uint64, 2)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	h.disp.Invoke("__syscall_lstat64", h.mod(m), stack, []byte{0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_getcwd(m *Module, l0 int32, l1 int32) int32 {
	stack := make([]uint64, 2)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	h.disp.Invoke("__syscall_getcwd", h.mod(m), stack, []byte{0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Emscripten_get_now(m *Module) float64 {
	stack := make([]uint64, 1)
	h.disp.Invoke("emscripten_get_now", h.mod(m), stack, []byte{}, []byte{0x7c})
	return api.DecodeF64(stack[0])
}

func (h *host) X__syscall_mkdirat(m *Module, l0 int32, l1 int32, l2 int32) int32 {
	stack := make([]uint64, 3)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	h.disp.Invoke("__syscall_mkdirat", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X_mktime_js(m *Module, l0 int32) int64 {
	stack := make([]uint64, 1)
	stack[0] = api.EncodeI32(l0)
	h.disp.Invoke("_mktime_js", h.mod(m), stack, []byte{0x7f}, []byte{0x7e})
	return int64(stack[0])
}

func (h *host) X_localtime_js(m *Module, l0 int64, l1 int32) {
	stack := make([]uint64, 2)
	stack[0] = api.EncodeI64(l0)
	stack[1] = api.EncodeI32(l1)
	h.disp.Invoke("_localtime_js", h.mod(m), stack, []byte{0x7e, 0x7f}, []byte{})
}

func (h *host) X_munmap_js(m *Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int64) int32 {
	stack := make([]uint64, 6)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	stack[4] = api.EncodeI32(l4)
	stack[5] = api.EncodeI64(l5)
	h.disp.Invoke("_munmap_js", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f, 0x7f, 0x7e}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X_mmap_js(m *Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int64, l5 int32, l6 int32) int32 {
	stack := make([]uint64, 7)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	stack[4] = api.EncodeI64(l4)
	stack[5] = api.EncodeI32(l5)
	stack[6] = api.EncodeI32(l6)
	h.disp.Invoke("_mmap_js", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f, 0x7e, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_fadvise64(m *Module, l0 int32, l1 int64, l2 int64, l3 int32) int32 {
	stack := make([]uint64, 4)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI64(l1)
	stack[2] = api.EncodeI64(l2)
	stack[3] = api.EncodeI32(l3)
	h.disp.Invoke("__syscall_fadvise64", h.mod(m), stack, []byte{0x7f, 0x7e, 0x7e, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X_emscripten_runtime_keepalive_clear(m *Module) {
	stack := make([]uint64, 0)
	h.disp.Invoke("_emscripten_runtime_keepalive_clear", h.mod(m), stack, []byte{}, []byte{})
}

func (h *host) X__call_sighandler(m *Module, l0 int32, l1 int32) {
	stack := make([]uint64, 2)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	h.disp.Invoke("__call_sighandler", h.mod(m), stack, []byte{0x7f, 0x7f}, []byte{})
}

func (h *host) X__syscall_getdents64(m *Module, l0 int32, l1 int32, l2 int32) int32 {
	stack := make([]uint64, 3)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	h.disp.Invoke("__syscall_getdents64", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_readlinkat(m *Module, l0 int32, l1 int32, l2 int32, l3 int32) int32 {
	stack := make([]uint64, 4)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	h.disp.Invoke("__syscall_readlinkat", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_rmdir(m *Module, l0 int32) int32 {
	stack := make([]uint64, 1)
	stack[0] = api.EncodeI32(l0)
	h.disp.Invoke("__syscall_rmdir", h.mod(m), stack, []byte{0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X_setitimer_js(m *Module, l0 int32, l1 float64) int32 {
	stack := make([]uint64, 2)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeF64(l1)
	h.disp.Invoke("_setitimer_js", h.mod(m), stack, []byte{0x7f, 0x7c}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_symlinkat(m *Module, l0 int32, l1 int32, l2 int32) int32 {
	stack := make([]uint64, 3)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	h.disp.Invoke("__syscall_symlinkat", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) X__syscall_unlinkat(m *Module, l0 int32, l1 int32, l2 int32) int32 {
	stack := make([]uint64, 3)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	h.disp.Invoke("__syscall_unlinkat", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Emscripten_resize_heap(m *Module, l0 int32) int32 {
	newLen := uint64(uint32(l0))
	if newLen <= m.memSize.Load() {
		return 1
	}
	if newLen > uint64(cap(m.memory)) {
		return 0
	}
	m.memory = m.memory[:newLen]
	m.memSize.Store(newLen)
	return 1
}

func (h *host) X_emscripten_throw_longjmp(m *Module) {
	// cooperative unwind: __THREW__ already set; just return
}

func (h *host) Fd_close(m *Module, l0 int32) int32 {
	stack := make([]uint64, 1)
	stack[0] = api.EncodeI32(l0)
	h.disp.Invoke("fd_close", h.mod(m), stack, []byte{0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Fd_write(m *Module, l0 int32, l1 int32, l2 int32, l3 int32) int32 {
	stack := make([]uint64, 4)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	h.disp.Invoke("fd_write", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Fd_read(m *Module, l0 int32, l1 int32, l2 int32, l3 int32) int32 {
	stack := make([]uint64, 4)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	h.disp.Invoke("fd_read", h.mod(m), stack, []byte{0x7f, 0x7f, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Fd_sync(m *Module, l0 int32) int32 {
	stack := make([]uint64, 1)
	stack[0] = api.EncodeI32(l0)
	h.disp.Invoke("fd_sync", h.mod(m), stack, []byte{0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Environ_sizes_get(m *Module, l0 int32, l1 int32) int32 {
	stack := make([]uint64, 2)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	h.disp.Invoke("environ_sizes_get", h.mod(m), stack, []byte{0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Environ_get(m *Module, l0 int32, l1 int32) int32 {
	stack := make([]uint64, 2)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	h.disp.Invoke("environ_get", h.mod(m), stack, []byte{0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Fd_fdstat_get(m *Module, l0 int32, l1 int32) int32 {
	stack := make([]uint64, 2)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI32(l1)
	h.disp.Invoke("fd_fdstat_get", h.mod(m), stack, []byte{0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Fd_seek(m *Module, l0 int32, l1 int64, l2 int32, l3 int32) int32 {
	stack := make([]uint64, 4)
	stack[0] = api.EncodeI32(l0)
	stack[1] = api.EncodeI64(l1)
	stack[2] = api.EncodeI32(l2)
	stack[3] = api.EncodeI32(l3)
	h.disp.Invoke("fd_seek", h.mod(m), stack, []byte{0x7f, 0x7e, 0x7f, 0x7f}, []byte{0x7f})
	return api.DecodeI32(stack[0])
}

func (h *host) Proc_exit(m *Module, l0 int32) {
	stack := make([]uint64, 1)
	stack[0] = api.EncodeI32(l0)
	h.disp.Invoke("proc_exit", h.mod(m), stack, []byte{0x7f}, []byte{})
}

type aotModule struct {
	m    *Module
	disp *emcompat.AOTDispatch
}

func (a *aotModule) Memory() []byte              { return a.m.memory }
func (a *aotModule) ApplyDataRelocs()            { a.m.WasmApplyDataRelocs() }
func (a *aotModule) CallCtors()                  { a.m.WasmCallCtors() }
func (a *aotModule) SP() int32                   { return a.m.g0 }
func (a *aotModule) SetSP(v int32)               { a.m.g0 = v }
func (a *aotModule) SetStdout(w io.Writer)       { a.disp.SetStdout(w) }
func (a *aotModule) SetStderr(w io.Writer)       { a.disp.SetStderr(w) }
func (a *aotModule) SetStdoutCapture(bb *[]byte) { a.disp.SetStdoutCapture(bb) }

func (a *aotModule) Call(name string, args []uint64) uint64 { return aotCall(a.m, name, args) }

// aotCall dispatches an exported function by name (wasm value lanes).
func aotCall(m *Module, name string, args []uint64) uint64 {
	switch name {
	case "__wasm_call_ctors":
		m.WasmCallCtors()
		return 0
	case "__main_argc_argv":
		return uint64(uint32(m.MainArgcArgv(aotI32(args[0]), aotI32(args[1]))))
	case "pgl_set_popen_fn":
		m.PglSetPopenFn(aotI32(args[0]))
		return 0
	case "fclose":
		return uint64(uint32(m.Fclose(aotI32(args[0]))))
	case "fflush":
		return uint64(uint32(m.Fflush(aotI32(args[0]))))
	case "_emscripten_stack_alloc":
		return uint64(uint32(m.EmscriptenStackAlloc(aotI32(args[0]))))
	case "emscripten_builtin_memalign":
		return uint64(uint32(m.EmscriptenBuiltinMemalign(aotI32(args[0]), aotI32(args[1]))))
	case "__wasm_apply_data_relocs":
		m.WasmApplyDataRelocs()
		return 0
	case "pgl_set_system_fn":
		m.PglSetSystemFn(aotI32(args[0]))
		return 0
	case "pgl_set_pclose_fn":
		m.PglSetPcloseFn(aotI32(args[0]))
		return 0
	case "fopen":
		return uint64(uint32(m.Fopen(aotI32(args[0]), aotI32(args[1]))))
	case "malloc":
		return uint64(uint32(m.Malloc(aotI32(args[0]))))
	default:
		panic("aot: unknown export " + name)
	}
}

// RegisterRW appends the socket read/write callbacks (ptr i32, len i32 -> i32,
// matching the wazero backend) and returns the base index.
func (a *aotModule) RegisterRW(read func(dst []byte) int, write func(src []byte)) uint32 {
	idx := uint32(len(a.m.t0))
	readFn := func(m *Module, ptr, max int32) int32 {
		tmp := make([]byte, max)
		n := read(tmp)
		if n > 0 {
			copy(m.memory[ptr:ptr+int32(n)], tmp[:n])
		}
		return int32(n)
	}
	writeFn := func(m *Module, ptr, length int32) int32 {
		write(m.memory[ptr : ptr+length])
		return length
	}
	a.m.t0 = append(a.m.t0, readFn, writeFn)
	return idx
}

// RegisterInitdb gives the callbacks module access (readCString, Fopen via
// exports) and appends the system/popen/pclose table entries.
func (a *aotModule) RegisterInitdb(cb *emcompat.InitdbCallbacks) uint32 {
	cb.SetModule(emcompat.NewAOTModuleAdapter(func() []byte { return a.m.memory }, func(n string, ar []uint64) uint64 { return aotCall(a.m, n, ar) }))
	idx := uint32(len(a.m.t0))
	systemFn := func(m *Module, cmd int32) int32 {
		return cb.OnSystem(context.Background(), aotCStr(m.memory, cmd))
	}
	popenFn := func(m *Module, cmd, mode int32) int32 {
		return cb.OnPopen(context.Background(), aotCStr(m.memory, cmd), aotCStr(m.memory, mode))
	}
	pcloseFn := func(m *Module, stream int32) int32 {
		return cb.OnPclose(context.Background(), stream)
	}
	a.m.t0 = append(a.m.t0, systemFn, popenFn, pcloseFn)
	return idx
}

func aotCStr(mem []byte, ptr int32) string {
	if ptr == 0 {
		return ""
	}
	end := int(ptr)
	for end < len(mem) && mem[end] != 0 {
		end++
	}
	return string(mem[ptr:end])
}

// NewAOT wires the host adapter, instantiates the transpiled module with
// headroom for emscripten_resize_heap to grow by reslicing (no realloc,
// so cached m.M stays valid), and returns it as an emcompat.AOTModule.
func NewAOT(fs *vfs.FS, stdin []byte, capture *[]byte) emcompat.AOTModule {
	h := &host{fs: fs, stdin: stdin, capture: capture, disp: emcompat.NewAOTDispatch(fs, stdin, capture)}
	return &aotModule{m: NewWithWASIReserve(h, h, 768<<20), disp: h.disp}
}

func aotI32(v uint64) int32 { return int32(uint32(v)) }

var _ = context.Background
